categorical_groups: {}
cell_type: LSTM
dropout: 0.12996809454070027
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_size: 70
learning_rate: 0.08610695514315213
log_gradient_flow: false
log_interval: 10
log_val_interval: 1
monotone_constaints: {}
n_plotting_samples: null
n_validation_samples: null
optimizer: Ranger
optimizer_params: null
output_transformer: !!python/object:pytorch_forecasting.data.encoders.GroupNormalizer
  center: true
  groups: []
  method: standard
  method_kwargs: {}
  norm_:
    center: !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      jaSmclpGpbw=
    scale: !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      AAAAAAAE8D8=
  scale_by_group: false
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
rnn_layers: 2
static_categoricals: []
static_reals: []
target: Power_Usage
target_lags: {}
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- DoW_Friday
- DoW_Monday
- DoW_Saturday
- DoW_Sunday
- DoW_Thursday
- DoW_Tuesday
- DoW_Wednesday
- Humidity
- Man_Cost
- Power_Cost
- Production
- Temperature
- Worker_Power
- time_idx
time_varying_reals_encoder:
- DoW_Friday
- DoW_Monday
- DoW_Saturday
- DoW_Sunday
- DoW_Thursday
- DoW_Tuesday
- DoW_Wednesday
- Humidity
- Man_Cost
- Power_Cost
- Production
- Temperature
- Worker_Power
- time_idx
- Power_Usage
weight_decay: 0.03703792193114575
x_categoricals: []
x_reals:
- DoW_Friday
- DoW_Monday
- DoW_Saturday
- DoW_Sunday
- DoW_Thursday
- DoW_Tuesday
- DoW_Wednesday
- Humidity
- Man_Cost
- Power_Cost
- Production
- Temperature
- Worker_Power
- time_idx
- Power_Usage
